version: "3.9"
services:
  client-backend:
    image: mars-back-image
    container_name: mars-back
    build:
      context: .
      dockerfile: DockerfileBack
    ports:
      - 8290:8290
    environment:
      - SERVER_PORT= 8290
  frontend:
    image: frontend-nextjs
    container_name: frontend
    build:
      context: ./front
      dockerfile: Dockerfile.front
    ports:
      - 8080:3000

networks:
  backend:
    name: backend
    external: true
    driver: bridge
