version: "3.9"
services:
  service-db:
    container_name: mars-db
    image: postgres:16
    environment:
      POSTGRES_DB: mars-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pass
    volumes:
      - mars-data:/var/lib/postgresql/data-mars
    ports:
      - "5432:5432"
    networks:
      - backend

  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minio
    environment:
      MINIO_ROOT_USER: "user1"
      MINIO_ROOT_PASSWORD: "password1"
      MINIO_DEFAULT_BUCKETS: bucket1
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend

volumes:
  mars-data: { }
  minio-data: { }

networks:
  backend:
    name: backend
    external: true
    driver: bridge
