server:
  port: 8290
  servlet:
    context-path: /
logging:
  level:
    root: DEBUG
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
  datasource:
    #url: jdbc:postgresql://host.docker.internal:5432/mars-db
    url: jdbc:postgresql://localhost:5432/mars-db
    username: root
    password: root_pass
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8
    connectionProperties: useUnicode=true;characterEncoding=utf-8;
    jpa:
      properties:
        hibernate:
          generate_statistics: true
    minio:
      #url: http://host.docker.internal:9000
      url: http://localhost:9000
      bucket: bucket1
      access-key: Q3AM3UQ867SPQQA43P2F
      secret-key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351