import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider, Flex } from "antd";
import { SWRConfig } from "swr";
import SWCProvider from "@/component/SWCProvider";
import ruRU from "antd/locale/ru_RU";
import AxiosInstanceProvider from "@/context/axiosContext";
import { createContext } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const BASE_URL = process.env.NEXT_PUBLIC_BACKEND_CLIENT_URL;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-[100vh]`}>
        <Flex className="h-full">
          <AxiosInstanceProvider
            config={{
              baseURL: BASE_URL || "cosijdcsiojsdcio",
            }}
          >
            <SWCProvider>
              <ConfigProvider locale={ruRU}>
                <AntdRegistry>{children}</AntdRegistry>
              </ConfigProvider>
            </SWCProvider>
          </AxiosInstanceProvider>
        </Flex>
      </body>
    </html>
  );
}
